;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	ac-clang-async-autocomplete-autotrigger
	c-electric-colon
	c-electric-delete-forward
	c-electric-paren
	c-electric-semi&comma
	c-electric-slash
	c-electric-star
	c-indent-line-or-region
	dabbrev-expand
	indent-for-tab-command
	jorbi/toggle-comment-line
	org-cycle
	org-force-self-insert
	org-metaleft
	org-self-insert-command
	org-yank
	paredit-backward-kill-word
	paredit-semicolon
	python-indent-dedent-line-backspace
	slime-space
	))

(setq mc/cmds-to-run-once
      '(
	abort-recursive-edit
	eval-defun
	smex
	))
