;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-paren
	c-electric-semi&comma
	c-indent-line-or-region
	dabbrev-expand
	indent-for-tab-command
	jorbi/toggle-comment-line
	org-cycle
	org-force-self-insert
	org-metaleft
	org-self-insert-command
	python-indent-dedent-line-backspace
	))

(setq mc/cmds-to-run-once
      '(
	smex
	))
